DROP VIEW IF EXISTS view_ninjas_clans;
DROP VIEW IF EXISTS view_missions_status;
DROP VIEW IF EXISTS view_teams_participants;
DROP VIEW IF EXISTS view_duels_results;
DROP VIEW IF EXISTS view_artifacts_archs;

DROP TABLE jinchuriki;
DROP TABLE weapon_ninja;
DROP TABLE duels;
DROP TABLE artifact;
DROP TABLE weapon;
DROP TABLE tailed_beast;
DROP TABLE missions;
DROP TABLE jutsu_list;
DROP TABLE places;
DROP TABLE ninjas;
DROP TABLE organisations;
DROP TABLE teams;
DROP TABLE clans;
DROP TABLE arch;
DROP TABLE village;
