DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS channels_channel_id_seq;
DROP SEQUENCE IF EXISTS videos_video_id_seq;
DROP SEQUENCE IF EXISTS comments_comment_id_seq;
DROP SEQUENCE IF EXISTS video_likes_like_id_seq;
DROP SEQUENCE IF EXISTS subscriptions_subscription_id_seq;
DROP SEQUENCE IF EXISTS playlists_playlist_id_seq;
DROP SEQUENCE IF EXISTS categories_category_id_seq;
DROP SEQUENCE IF EXISTS video_categories_video_category_id_seq;
DROP SEQUENCE IF EXISTS notifications_notification_id_seq;
DROP SEQUENCE IF EXISTS reports_report_id_seq;
DROP SEQUENCE IF EXISTS ads_ad_id_seq;
DROP SEQUENCE IF EXISTS user_history_video_id_seq;
DROP SEQUENCE IF EXISTS tags_tag_id_seq;
DROP SEQUENCE IF EXISTS playlist_videos_playlist_video_id_seq;

CREATE SEQUENCE users_id_seq;
CREATE SEQUENCE channels_channel_id_seq;
CREATE SEQUENCE videos_video_id_seq;
CREATE SEQUENCE comments_comment_id_seq;
CREATE SEQUENCE video_likes_like_id_seq;
CREATE SEQUENCE subscriptions_subscription_id_seq;
CREATE SEQUENCE playlists_playlist_id_seq;
CREATE SEQUENCE categories_category_id_seq;
CREATE SEQUENCE video_categories_video_category_id_seq;
CREATE SEQUENCE notifications_notification_id_seq;
CREATE SEQUENCE reports_report_id_seq;
CREATE SEQUENCE ads_ad_id_seq;
CREATE SEQUENCE user_history_video_id_seq;
CREATE SEQUENCE tags_tag_id_seq;
CREATE SEQUENCE playlist_videos_playlist_video_id_seq;